### GET ONE
GET http://localhost:4000/image/60b7a9add889b54ac45a863c

### POST ONE

POST http://localhost:4000/image
Content-Type: multipart/form-data; boundary=ROW

--ROW
Content-Disposition: form-data; name="img"; filename="earth.jpeg"
Content-Type: image/jpeg

< ./earth.jpeg
--ROW--