### GET ALL 
GET http://localhost:4000/orders

### GET ONE BY ID
GET http://localhost:4000/orders/60b4dee00678ee127eb97573

### DELETE BY ID
DELETE http://localhost:4000/orders/60ac96ae79fbf03332fddfe1

### POST ONE
POST http://localhost:4000/orders
Content-Type: application/json

{
    "customer": "60acb52f33c12941ea7cbead",
    "address": {
        "street": "Folkungagatan 5",
        "zipcode": "41102",
        "city": "Gothenburg",
        "country": "Sweden"
    }, 
    "items": ["Shades", "Umbrella", "Watch"],
    "payment": "PayPal",
    "delivery": {
        "name": "DHL",
        "price": 20,
        "deliveryTime": "1-3 days"
    }, 
    "sum": 1599
}

### UPDATE ONE BY ID
PUT http://localhost:4000/orders/60a76e9911323ed1e9e7233a
Content-Type: application/json

{
    "customer": "Oscar Andersson"
}