### GET ALL 
GET http://localhost:4000/orders

### GET ONE BY ID
GET http://localhost:4000/orders/60a75f96cb083cca3d16ab6e

### DELETE BY ID
DELETE http://localhost:4000/orders/60a76052e58942cae3df2c36

### POST ONE
POST http://localhost:4000/orders
Content-Type: application/json

{
    "customer": "Herman Wikström",
    "items": ["Shoes", "Bag", "Shades"],
    "date": "2021-05-21",
    "payment": "Mastercard",
    "delivery": "DHL", 
    "sum": 1599
}

### UPDATE ONE BY ID
PUT http://localhost:4000/orders/60a763338148fcccbe4e8347
Content-Type: application/json

{
    "customer": "Herman Berglund"
}