### GET ALL 
GET http://localhost:4000/products

### GET ONE BY ID
GET http://localhost:4000/products/60a5146db931ca41af97a026

### DELETE BY ID
DELETE http://localhost:4000/products/60b0978bc3e06d135143e294

### POST ONE
POST http://localhost:4000/products
Content-Type: multipart/form-data

{
    "category": "Accessories",
    "name": "parser",
    "price": 200,
    "img": "https://images.unsplash.com/photo-1621570359164-ad2429a2c93b",
    "description": "Baggy wear his ugly bag",
    "details": "Bhaggy is ugly with his bag",
    "care": "Don't wash",
    "stock": 100
}

### UPDATE ONE BY ID
PUT http://localhost:4000/products/60b63dd13829b28c5ccefa12
Content-Type: application/json

{
    "price": 100
}