### GET ALL 
GET http://localhost:4000/users

### GET ONE BY ID
GET http://localhost:4000/users/60acccf5f6bb064989f05e5c

### DELETE BY ID
DELETE http://localhost:4000/users/60acb3080925fd4101a26cca

### POST ONE
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "email": "victor.wikstrom@icloud.com",
    "password": "asdasd",
    "role": "admin",
    "authorizedAdmin": true,
    "fullName": "Victor Wikström",
    "phone": "0702045411",
    "address": {
        "street": "Jenny Lindsgatan 4B",
        "zipcode": "41662",
        "city": "Gothenburg",
        "country": "Sweden"
    }
}


### UPDATE ONE BY ID
PUT http://localhost:4000/users/60acb3080925fd4101a26cca
Content-Type: application/json

{
    "fullName": "Oscar Andersson"
}

### LOGIN 
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "victor.wikstrom@icloud.com",
    "password": "asdasd"
}

### LOGIN ADMIN
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "herman@herman.se",
    "password": "123"
}

### AUTHENTICATE / CHECK COOKIE
GET http://localhost:4000/users/authenticate

### LOGOUT
DELETE http://localhost:4000/users/logout