### GET ALL 
GET http://localhost:4000/users

### GET ONE BY ID
GET http://localhost:4000/users/60b62e6a4f6ac5511d6343c8

### DELETE BY ID
DELETE http://localhost:4000/users/60b5f7f48294663aeef80ba1

### POST ONE / REGISTER
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "email": "osse2@gmail.com",
    "password": "hejhej1",
    "role": "customer",
    "authorizedAdmin": false,
    "fullName": "Oscar Andersson",
    "phone": "0702245411",
    "address": {
        "street": "Folkungagatan 5",
        "zipcode": "41662",
        "city": "Gothenburg",
        "country": "Sweden"
    }
}


### UPDATE ONE BY ID
PUT http://localhost:4000/users/60acb3080925fd4101a26cca
Content-Type: application/json

{
    "fullName": "Oscar Andersson"
}

### LOGIN 
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "oskarberglund97@hotmail.com",
    "password": "hejhej"
}

### LOGIN ADMIN
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "carro@gmail.com",
    "password": "hej"
}

### AUTHENTICATE / CHECK COOKIE
GET http://localhost:4000/users/authenticate

### LOGOUT
DELETE http://localhost:4000/users/logout