### GET ALL 
GET http://localhost:4000/users

### GET ONE BY ID
GET http://localhost:4000/users/60ab9cbcae0f471f176af423

### DELETE BY ID
DELETE http://localhost:4000/users/60ac93ce27a0012ec21cb9c7

### POST ONE
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "email": "crushcake@gmail.com",
    "password": "123",
    "role": "customer",
    "authorized": false,
    "fullName": "Oscar Andersson",
    "phone": "0705552233",
    "address": {
        "street": "Folkungagatan 5",
        "zipcode": "411 02",
        "city": "Gothenburg",
        "country": "Sweden"
    }
}

### LOGIN

### UPDATE ONE BY ID
PUT http://localhost:4000/users/60a61e190c6cacb773b30530
Content-Type: application/json

{
    "fullName": "Victor Wikström"
}